services:
  # Weaviate Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.25.3
    container_name: ai-interview-weaviate
    ports:
      - "8081:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-openai,text2vec-cohere,text2vec-huggingface,ref2vec-centroid,generative-openai,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/.well-known/ready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-interview-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEAVIATE_URL=http://weaviate:8080
      - WEAVIATE_API_KEY=${WEAVIATE_API_KEY}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=${DATABASE_URL}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
      - PHOENIX_ENDPOINT=${PHOENIX_ENDPOINT}
    depends_on:
      weaviate:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./lib:/app/lib
      - ./public:/app/public
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Phoenix for LLM Observability (Optional)
  phoenix:
    image: arizephoenix/phoenix:latest
    container_name: ai-interview-phoenix
    ports:
      - "6006:6006"
    environment:
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}
    restart: unless-stopped
    profiles:
      - observability

volumes:
  weaviate_data:
    driver: local

networks:
  default:
    name: ai-interview-network
